# encoding: utf-8
"""
    drive.keys
    ~~~~~~~~~~

    This file contains the keys used by :package:`drive`.
"""

k_bootstrap_code = 'bootstrap_code'
k_MBR = 'MBR'
k_Partition = 'Partition'
k_PartitionEntry = 'PartitionEntry'
k_PartitionEntries = 'PartitionEntries'
k_status = 'status'

k_starting_chs_address = 'starting_chs_address'
k_ignored = '__ignored__'
k_partition_type = 'partition_type'
k_ending_chs_address = 'ending_chs_address'
k_first_sector_address = 'first_sector_address'
k_first_byte_address = 'first_byte_address'
k_number_of_sectors = 'number_of_sectors'
k_size = 'size'

k_boot_signature = 'boot_signature'

k_FAT32BootSector = 'FAT32BootSector'
k_jump_instruction = 'jump_instruction'
k_OEM_name = 'OEM_name'
k_bytes_per_sector = 'bytes_per_sector'
k_sectors_per_cluster = 'sectors_per_cluster'
k_number_of_reserved_sectors = 'number_of_reserved_sectors'
k_number_of_FATs = 'number_of_FATs'
k_media_descriptor = 'media_descriptor'
k_sectors_per_track = 'sectors_per_track'
k_number_of_heads = 'number_of_heads'
k_number_of_hidden_sectors = 'number_of_hidden_sectors'
k_sectors_per_FAT = 'sectors_per_FAT'
k_drive_description = 'drive_description'
k_version = 'version'
k_cluster_number_of_root_directory_start =\
    'cluster_number_of_root_directory_start'
k_sector_number_of_FS_info_sector = 'sector_number_of_FS_info_sector'
k_sector_number_of_boot_sectors_backup = 'sector_number_of_boot_sectors_backup'
k_drive_number = 'drive_number'
k_extended_boot_signature = 'extended_boot_signature'
k_volume_id = 'volume_id'
k_volume_label = 'volume_label'
k_filesystem_type = 'filesystem_type'

k_FAT32FileAllocationTable = 'FAT32FileAllocationTable'

k_Drive = 'Drive'

k_FAT32 = 'FAT32'
k_NTFS = 'NTFS'
k_ExtendedPartition = 'ExtendedPartition'

k_reserved = 'reserved'

k_FAT32DirectoryTableEntry = 'FAT32DirectoryTableEntry'
k_short_file_name = 'short_file_name'
k_short_extension = 'short_extension'
k_attribute = 'attribute'
k_create_time_10ms = 'create_time_10ms'
k_create_time = 'create_time'
k_create_date = 'create_date'
k_access_date = 'access_date'
k_higher_cluster = 'higher_cluster'
k_modify_time = 'modify_time'
k_modify_date = 'modify_date'
k_lower_cluster = 'lower_cluster'
k_file_length = 'file_length'

k_FAT32LongFilenameEntry = 'FAT32LongFilenameEntry'
k_sequence_number = 'sequence_number'
k_name_1 = 'name_1'
k_type = 'type'
k_checksum = 'checksum'
k_name_2 = 'name_2'
k_first_cluster = 'first_cluster'
k_name_3 = 'name_3'

k_filename = 'filename'
k_full_path = 'full_path'
k_path = 'path'
k_extension = 'k_extension'
k_cluster_list = 'cluster_list'

k_NTFSBootSector = 'NTFSBootSector'
k_cluster_number_of_MFT_start = 'cluster_number_of_MFT_start'
k_cluster_number_of_MFT_mirror_start = 'cluster_number_of_MFT_mirror_start'
k_clusters_per_MFT_record = 'clusters_per_MFT_record'
k_bytes_per_MFT_record = 'bytes_per_MFT_record'
k_clusters_per_index_record = 'clusters_per_index_record'
k_bytes_per_index_record = 'bytes_per_index_record'
k_serial_number = 'serial_number'

k_FileRecordHeader = 'FileRecordHeader'
k_offset_to_update_sequence = 'offset_to_update_sequence'
k_size_of_update_sequence = 'size_of_update_sequence'
k_logfile_sequence_number = 'logfile_sequence_number'
k_offset_to_first_attribute = 'offset_to_first_attribute'
k_flags = 'flags'
k_logical_size = 'logical_size'
k_allocated_size = 'allocated_size'
k_base_record_index = 'base_record_index'
k_id_of_next_attribute = 'id_of_next_attribute'
k_number_of_this_record = 'number_of_this_record'
k_update_sequence_number = 'update_sequence_number'

k_common_header = 'common_header'
k_attribute_type = 'attribute_type'
k_size_of_attribute = 'size_of_attribute'
k_is_resident = 'is_resident'
k_length_of_name = 'length_of_name'
k_offset_to_name = 'offset_to_name'
k_attribute_id = 'attribute_id'
k_resident_header = 'resident_header'
k_size_of_attribute_content = 'size_of_attribute_content'
k_offset_to_attribute_content = 'offset_to_attribute_content'
k_is_indexed = 'is_indexed'
k_non_resident_header = 'non_resident_header'
k_starting_vcn_of_data_runs = 'starting_vcn_of_data_runs'
k_ending_vcn_of_data_runs = 'ending_vcn_of_data_runs'
k_offset_to_data_runs = 'offset_to_data_runs'
k_compression_unit = 'compression_unit'
k_initial_size = 'initial_size'

k_MFT_change_time = 'MFT_change_time'
k_access_time = 'access_time'
k_maximum_version_number = 'maximum_version_number'
k_version_number = 'version_number'
k_class_id = 'class_id'

k_parent_reference = 'parent_reference'
k_filename_namespace = 'filename_namespace'

k_GUID_object_id = 'GUID_object_id'
k_GUID_birth_volume_id = 'GUID_birth_volume_id'
k_GUID_birth_object_id = 'GUID_birth_object_id'
k_GUID_domain_id = 'GUID_domain_id'
